import Foundation

/// Upstream tables that test a *function* rather than a recognizer.
///
/// `RecognizerCorpus` describes the shape `extract_fixtures.py` understands:
/// a text, a match count, positions. A unit test of a value type has none of
/// those, which is why eight tables of `RecognizerResult` span algebra sat in
/// the `skipped` list under "unsupported shape" — the shape the extractor could
/// not express, not behaviour that did not matter. Those predicates are what
/// `remove_duplicates` and the conflict resolver are built on.
///
/// Generated by
/// [`Tools/extract_operation_cases.py`](../../Tools/extract_operation_cases.py).
public struct OperationCorpus: Decodable, Sendable {

    /// One boolean assertion about a pair of results.
    public struct Predicate: Decodable, Sendable {
        /// A `RecognizerResult` as the upstream test constructs it: four
        /// positional arguments, all literals.
        public struct Value: Decodable, Sendable {
            public let entityType: String
            public let score: Double
            public let start: Int
            public let end: Int

            enum CodingKeys: String, CodingKey {
                case entityType = "entity_type"
                case score, start, end
            }
        }

        public let file: String
        public let test: String
        /// `contains`, `contained_in`, `equal_indices`, `has_conflict`,
        /// `intersects`, `greater_than`, `equal`, `hash_equal`.
        public let op: String
        public let first: Value
        public let second: Value
        public let expected: Bool
    }

    /// One call of a pure function against a literal expectation.
    ///
    /// `expected` and the arguments are heterogeneous — a string, a bool, a
    /// list of pairs — so they arrive as `JSONValue` and each case is decoded
    /// by the test that knows what the function takes.
    public struct Function: Decodable, Sendable {
        public let file: String
        public let test: String
        /// Dotted Python name, e.g. `EntityRecognizer.sanitize_value`.
        public let function: String
        public let args: [JSONValue]
        public let expected: JSONValue
    }

    /// A list of results through a function, with assertions about the
    /// survivors.
    ///
    /// This is the shape that makes the predicates worth having:
    /// `remove_duplicates` is what consumes them, and its behaviour does not
    /// follow from theirs. It dedupes on equality, sorts by a key that omits the
    /// entity type, drops zero scores, then removes anything contained in a
    /// survivor of the same type.
    public struct Pipeline: Decodable, Sendable {
        public struct Field: Decodable, Sendable {
            public let index: Int
            public let field: String
            public let value: JSONValue
        }

        public let file: String
        public let test: String
        public let function: String
        public let input: [Predicate.Value]
        public let expectedCount: Int
        public let expectedFields: [Field]

        enum CodingKeys: String, CodingKey {
            case file, test, function, input
            case expectedCount = "expected_count"
            case expectedFields = "expected_fields"
        }
    }

    public struct Skipped: Decodable, Sendable {
        public let file: String
        public let test: String?
        public let reason: String
    }

    public let predicates: [Predicate]
    public let functions: [Function]
    public let pipelines: [Pipeline]
    /// Tables no corpus covers, each with a reason.
    public let skipped: [Skipped]
    /// Tables this tool cannot read but `extract_fixtures.py` already harvests.
    /// Recorded separately because reporting them as gaps overstated the gap.
    public let coveredElsewhere: [Skipped]

    enum CodingKeys: String, CodingKey {
        case predicates, functions, pipelines, skipped
        case coveredElsewhere = "covered_elsewhere"
    }
}

/// Just enough JSON to carry an upstream parameter through to Swift.
///
/// The alternative was a generator that emits per-function Swift types, which
/// would mean regenerating code rather than data every time upstream adds a row.
public enum JSONValue: Decodable, Sendable, Equatable {
    case string(String)
    case bool(Bool)
    case int(Int)
    case double(Double)
    case array([JSONValue])
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let value = try? container.decode(Bool.self) {
            self = .bool(value)
        } else if let value = try? container.decode(Int.self) {
            self = .int(value)
        } else if let value = try? container.decode(Double.self) {
            self = .double(value)
        } else if let value = try? container.decode(String.self) {
            self = .string(value)
        } else {
            self = .array(try container.decode([JSONValue].self))
        }
    }

    public var asString: String? {
        if case .string(let value) = self { return value }
        return nil
    }

    public var asBool: Bool? {
        if case .bool(let value) = self { return value }
        return nil
    }

    public var asInt: Int? {
        if case .int(let value) = self { return value }
        return nil
    }

    /// A score, which JSON may have delivered as either `0.5` or `0`.
    public var asDouble: Double? {
        switch self {
        case .double(let value): return value
        case .int(let value): return Double(value)
        default: return nil
        }
    }

    public var asArray: [JSONValue]? {
        if case .array(let value) = self { return value }
        return nil
    }

    /// A list of `(find, replace)` pairs, as `sanitize_value` takes.
    ///
    /// Upstream's second row passes `""` rather than a list — Python iterates
    /// an empty string into no pairs at all — so an empty string is not a
    /// malformed row, it is the "no replacements" case.
    public var asReplacementPairs: [(String, String)]? {
        if case .string(let text) = self, text.isEmpty { return [] }
        guard let rows = asArray else { return nil }
        var pairs: [(String, String)] = []
        for row in rows {
            guard let pair = row.asArray, pair.count == 2,
                  let find = pair[0].asString, let replace = pair[1].asString
            else { return nil }
            pairs.append((find, replace))
        }
        return pairs
    }
}
