import Testing
import Foundation
import PresidioConformance
import PresidioEngine
import PresidioAnalyzer

/// Which recognizers a registry loads, per language, against upstream's own
/// loader.
///
/// This suite exists because two bugs hid here for the entire life of the port,
/// and both were invisible to every other test: the English engine was correct,
/// so nothing failed, while every other language quietly got the wrong set.
///
/// The rule that was got wrong: an entry in `default_recognizers.yaml` which
/// omits `supported_languages` is **not** English-only. Upstream instantiates
/// it once per *requested* language. Eleven entries rely on that — e-mail, IP,
/// URL, IBAN, phone, crypto, date, MAC, UUID, medical licence — which is why a
/// Spanish engine should hold 13 recognizers and used to hold 2.
///
/// The gold file is generated by `Tools/registry_reference.py` from upstream's
/// `RecognizerListLoader`, so this compares against the real thing rather than
/// against a reading of its documentation.
@Suite("registry language expansion")
struct RegistryLanguageTests {

    struct Gold: Decodable {
        struct Row: Decodable {
            let name: String
            let `class`: String
            let language: String
            let entities: [String]
        }
        let presidioVersion: String
        let languages: [String: [Row]]

        enum CodingKeys: String, CodingKey {
            case presidioVersion = "presidio_version"
            case languages
        }
    }

    static let gold: Gold = {
        // swiftlint:disable:next force_try
        try! JSONDecoder().decode(Gold.self, from: Corpus.data(named: "registry_gold"))
    }()

    /// Recognizers this port has not implemented, and why they are excluded
    /// rather than counted as failures.
    ///
    /// `InVoterRecognizer` is the only entry in the language-agnostic group
    /// with no Swift implementation — it is disabled in the default config, so
    /// it never reaches a default registry in either implementation, and it is
    /// listed here so that stops being a coincidence nobody checked.
    static let notImplemented: Set<String> = []

    @Test("every targeted language loads exactly what upstream loads",
          arguments: ["en", "ru", "de", "fr", "it", "ja", "uk", "es", "pt", "zh"])
    func matchesUpstream(language: String) throws {
        let expected = try #require(Self.gold.languages[language])
        let want = Set(expected.map(\.name)).subtracting(Self.notImplemented)

        let registry = try RecognizerRegistry.loadPredefined(languages: [language])
        let got = Set(registry.recognizers.map(\.name))

        #expect(got == want, """
            \(language): missing \(want.subtracting(got).sorted()), \
            unexpected \(got.subtracting(want).sorted())
            """)
    }

    /// The bug in its most direct form: a recognizer declared under no language
    /// at all must still be built for whatever language was asked for.
    @Test("language-agnostic recognizers reach non-English registries")
    func agnosticRecognizersAreNotEnglishOnly() throws {
        for language in ["de", "ru", "ja", "zh", "uk", "pt", "fr"] {
            let registry = try RecognizerRegistry.loadPredefined(languages: [language])
            let names = Set(registry.recognizers.map(\.name))
            #expect(names.contains("EmailRecognizer"), "\(language) lost EmailRecognizer")
            #expect(names.contains("PhoneRecognizer"), "\(language) lost PhoneRecognizer")
            #expect(names.count == 10, "\(language) loaded \(names.count), expected 10")
        }
    }

    /// Every recognizer in a registry must answer to the language it was loaded
    /// for. A recognizer tagged `en` sitting in a Spanish registry is worse than
    /// a missing one: `recognizers(language:)` filters it out silently, so it
    /// looks present and never fires.
    @Test("loaded recognizers carry the language they were loaded for")
    func recognizersCarryTheirLanguage() throws {
        for language in ["en", "es", "it", "de", "ja"] {
            let registry = try RecognizerRegistry.loadPredefined(languages: [language])
            let wrong = registry.recognizers
                .filter { $0.supportedLanguage != language }
                .map(\.name)
            #expect(wrong.isEmpty, "\(language): mistagged \(wrong.sorted())")

            // ...and they must actually be selectable, which is the property
            // the tagging exists to produce.
            let selected = try registry.recognizers(language: language, allFields: true)
            #expect(selected.count == registry.recognizers.count)
        }
    }

    /// A multi-language request builds one instance per language, not one
    /// shared instance. Upstream does the same, and the engine relies on it:
    /// `recognizers(language:)` selects by exact match.
    @Test("a multi-language registry holds one instance per language")
    func multiLanguageRegistry() throws {
        let registry = try RecognizerRegistry.loadPredefined(languages: ["en", "es"])
        let english = try registry.recognizers(language: "en", allFields: true)
        let spanish = try registry.recognizers(language: "es", allFields: true)

        #expect(english.count == Self.gold.languages["en"]?.count)
        #expect(spanish.count == Self.gold.languages["es"]?.count)

        // Same class, two objects, two ids — otherwise context enhancement
        // routes results to whichever one hashed first.
        let ids = Set((english + spanish).map(\.id))
        #expect(ids.count == english.count + spanish.count)
    }

    /// Without a configuration the whole catalogue loads, and that path had the
    /// second bug: hand-written recognizers were appended for *every* language,
    /// so a Japanese registry came back holding three English ones.
    @Test("the no-configuration path also respects language")
    func wholeCatalogueRespectsLanguage() throws {
        for language in ["ja", "zh", "ru", "uk", "pt"] {
            let registry = try RecognizerRegistry.loadPredefined(
                languages: [language], configuration: nil
            )
            #expect(registry.recognizers.isEmpty, """
                \(language): catalogue has no recognizers for this language, \
                but \(registry.recognizers.map(\.name).sorted()) were loaded
                """)
        }
    }
}
