import Testing
import Foundation
import PresidioConformance
import PresidioCore
@testable import PresidioAnonymizer

/// Differential test against real Presidio.
///
/// The anonymizer's upstream tests are imperative, so instead of porting
/// assertions the reference is generated by *running* `presidio_anonymizer`
/// (see Tools/anonymizer_reference.py). Every case records the exact output
/// text and the exact operator-result spans, so this pins behaviour upstream
/// never explicitly asserted — index normalization, right-to-left rewriting,
/// and conflict resolution in particular.
@Suite("Anonymizer differential vs Python")
struct AnonymizerDifferentialTests {

    struct Reference: Decodable {
        struct Case: Decodable {
            struct AnalyzerResult: Decodable {
                let entityType: String
                let start: Int
                let end: Int
                let score: Double

                enum CodingKeys: String, CodingKey {
                    case entityType = "entity_type"
                    case start, end, score
                }
            }
            struct Config: Decodable {
                let operatorName: String
                let params: [String: Param]

                enum CodingKeys: String, CodingKey {
                    case operatorName = "operator_name"
                    case params
                }
            }
            struct Item: Decodable {
                let start: Int
                let end: Int
                let entityType: String
                let text: String
                let `operator`: String

                enum CodingKeys: String, CodingKey {
                    case entityType = "entity_type"
                    case start, end, text, `operator`
                }
            }
            struct Result: Decodable {
                let text: String
                let items: [Item]
            }

            let name: String
            let text: String
            let analyzerResults: [AnalyzerResult]
            let operators: [String: Config]
            let mergeEntitiesWithSpaces: Bool
            let conflictResolution: String
            let result: Result?
            let error: String?

            enum CodingKeys: String, CodingKey {
                case name, text, operators, result, error
                case analyzerResults = "analyzer_results"
                case mergeEntitiesWithSpaces = "merge_entities_with_spaces"
                case conflictResolution = "conflict_resolution"
            }
        }

        let stats: Stats
        let cases: [Case]

        struct Stats: Decodable { let cases: Int }
    }

    /// Python params are untyped; decode the shapes the generator emits.
    enum Param: Decodable {
        case string(String)
        case int(Int)
        case bool(Bool)

        init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            // Bool must be tried before Int: JSONDecoder will happily decode
            // `true` as 1 otherwise, turning from_end into chars_to_mask.
            if let value = try? container.decode(Bool.self) { self = .bool(value) }
            else if let value = try? container.decode(Int.self) { self = .int(value) }
            else { self = .string(try container.decode(String.self)) }
        }

        var operatorParam: OperatorParam {
            switch self {
            case .string(let value): return .string(value)
            case .int(let value): return .int(value)
            case .bool(let value): return .bool(value)
            }
        }
    }

    static let reference: Reference = {
        // swiftlint:disable:next force_try
        try! JSONDecoder().decode(
            Reference.self, from: Corpus.data(named: "anonymizer_reference")
        )
    }()

    @Test("the reference corpus is non-trivial")
    func corpusLoads() {
        #expect(Self.reference.cases.count >= 40)
        #expect(Self.reference.cases.allSatisfy { !$0.name.isEmpty })
    }

    @Test("output text and operator spans match Python exactly")
    func matchesPython() throws {
        var failures: [String] = []
        var checked = 0

        for testCase in Self.reference.cases {
            let results = testCase.analyzerResults.map {
                RecognizerResult(
                    entityType: $0.entityType, start: $0.start, end: $0.end, score: $0.score
                )
            }
            let configs = testCase.operators.mapValues { config in
                OperatorConfig(
                    config.operatorName,
                    config.params.mapValues(\.operatorParam)
                )
            }
            let strategy: ConflictResolutionStrategy =
                testCase.conflictResolution == "remove_intersections"
                ? .removeIntersections : .mergeSimilarOrContained

            let engine = AnonymizerEngine()
            let produced: EngineResult
            do {
                produced = try engine.anonymize(
                    text: testCase.text,
                    analyzerResults: results,
                    operators: configs,
                    conflictResolution: strategy,
                    mergeEntitiesWithSpaces: testCase.mergeEntitiesWithSpaces
                )
            } catch {
                if testCase.error == nil {
                    failures.append("\(testCase.name): threw \(error), Python succeeded")
                }
                continue
            }

            guard let expected = testCase.result else {
                failures.append("\(testCase.name): succeeded, Python raised \(testCase.error ?? "?")")
                continue
            }
            checked += 1

            if produced.text != expected.text {
                failures.append("""
                    \(testCase.name): text
                      python \(expected.text.debugDescription)
                      swift  \(produced.text.debugDescription)
                    """)
                continue
            }

            // Item order matters: upstream emits them end-to-start, and callers
            // rely on that to apply further edits without reindexing.
            let got = produced.items.map { [$0.start, $0.end, $0.text, $0.operator, $0.entityType] as [AnyHashable] }
            let want = expected.items.map { [$0.start, $0.end, $0.text, $0.operator, $0.entityType] as [AnyHashable] }
            if got != want {
                failures.append("""
                    \(testCase.name): items
                      python \(want)
                      swift  \(got)
                    """)
            }
        }

        #expect(checked >= 40, "only \(checked) cases compared")
        #expect(
            failures.isEmpty,
            """
            \(failures.count)/\(Self.reference.cases.count) cases diverge:
            \(failures.prefix(8).joined(separator: "\n"))
            """
        )
    }
}
