import Foundation
import PresidioAnalyzer

/// The recognizer catalogue, loaded from data extracted from Presidio.
///
/// Recognizers are data (`Resources/recognizers.json`, regenerated by
/// `Tools/extract_patterns.py`) rather than 82 hand-written Swift types. The
/// point is not the line count — it is that tracking an upstream release is
/// re-running a script instead of a hand merge across 82 files.
///
/// The parts that genuinely *are* code — checksum validators — live in
/// `ValidatorRegistry` and are attached by class name at build time.
public enum Catalog {

    public struct Definition: Codable, Sendable {
        public let `class`: String
        public let file: String
        public let entity: String?
        public let language: String
        public let country: String?
        public let patterns: [PatternSpec]
        public let context: [String]
        public let flags: [String]
        public let hasValidateResult: Bool
        public let hasInvalidateResult: Bool
        public let hasCustomAnalyze: Bool

        enum CodingKeys: String, CodingKey {
            case `class`, file, entity, language, country, patterns, context, flags
            case hasValidateResult = "has_validate_result"
            case hasInvalidateResult = "has_invalidate_result"
            case hasCustomAnalyze = "has_custom_analyze"
        }

        /// True when upstream implements behaviour this catalogue cannot express
        /// as data alone.
        public var needsSwiftLogic: Bool {
            hasValidateResult || hasInvalidateResult || hasCustomAnalyze
        }
    }

    public struct PatternSpec: Codable, Sendable {
        public let name: String?
        public let regex: String
        public let score: Double
    }

    public struct File: Codable, Sendable {
        public let schemaVersion: Int
        public let source: Source
        public let recognizers: [Definition]

        enum CodingKeys: String, CodingKey {
            case schemaVersion = "schema_version"
            case source, recognizers
        }
    }

    public struct Source: Codable, Sendable {
        public let repo: String
        public let commit: String
    }

    public enum CatalogError: Error, CustomStringConvertible {
        case resourceMissing

        public var description: String {
            """
            recognizers.json not found in the bundle. Regenerate with:
              python3 Tools/extract_patterns.py --presidio <checkout> \
            --out Sources/PresidioRecognizers/Resources/recognizers.json
            """
        }
    }

    public static func definitions() throws -> [Definition] {
        guard let url = Bundle.module.url(
            forResource: "recognizers", withExtension: "json"
        ) else { throw CatalogError.resourceMissing }
        return try JSONDecoder()
            .decode(File.self, from: Data(contentsOf: url))
            .recognizers
    }

    /// Build a recognizer, attaching any registered checksum logic.
    ///
    /// `logic` overrides the registry lookup, which is how a non-default
    /// fixture variant (e.g. DE_VAT_ID in strict mode) is exercised.
    public static func makeRecognizer(
        _ definition: Definition, logic: RecognizerLogic? = nil
    ) -> PatternRecognizer? {
        guard let entity = definition.entity else { return nil }
        return PatternRecognizer(
            name: definition.class,
            entity: entity,
            patterns: definition.patterns.enumerated().map { index, spec in
                Pattern(
                    name: spec.name ?? "\(definition.class)-\(index)",
                    regex: spec.regex,
                    score: spec.score
                )
            },
            context: definition.context,
            logic: logic ?? ValidatorRegistry.logic(for: definition.class),
            flags: RegexFlags(names: definition.flags),
            strategy: ValidatorRegistry.strategy(for: definition.class)
        )
    }

    /// Every recognizer that can currently be built.
    public static func allRecognizers() throws -> [PatternRecognizer] {
        try definitions().compactMap { makeRecognizer($0) }
    }
}
