#!/usr/bin/env python3
"""Harvest parametrize tables whose values are computed at import time.

`extract_fixtures.py` reads with `ast` only and never imports Presidio. That
is a deliberate contract: corpus regeneration works from a bare checkout with
no Python environment, which is what the CI reproducibility job relies on.

A few upstream tables put a computation in the table itself -- Nigeria's NIN
cases are generated by a Verhoeff routine at module scope -- so no static
evaluator can reach them. Rather than weaken the main extractor's guarantee,
this is a separate tool with a separate contract: it *does* import the test
module, so it needs the upstream package installed, and its output goes to its
own fixture file. `extract_fixtures.py` output stays byte-identical either way.

Tables are listed explicitly. A tool that imports arbitrary test modules and
harvests whatever it finds would be a much larger blast radius for very little
gain -- the static extractor already reaches 106 of 111 recognizer tables.

Usage:
    python3 Tools/extract_computed_fixtures.py --presidio <checkout> \\
        --python <venv python> \\
        --out Tests/PresidioConformance/Fixtures/computed_cases.json
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

# (test file relative to presidio-analyzer, test function, recognizer class,
#  entity list). Explicit, so adding one is a visible change.
TABLES = [
    (
        "tests/test_ng_nin_recognizer.py",
        "test_when_nin_in_text_then_all_ng_nins_found",
        "NgNinRecognizer",
        ["NG_NIN"],
    ),
]

CHILD = r'''
import importlib.util, json, os, sys

root, tables = sys.argv[1], json.loads(sys.argv[2])
sys.path.insert(0, root)
os.chdir(root)

out = []
for rel, test, recognizer, entities in tables:
    spec = importlib.util.spec_from_file_location("t_" + test, rel)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    fn = getattr(module, test)
    for mark in getattr(fn, "pytestmark", []):
        if mark.name != "parametrize":
            continue
        out.append({
            "file": rel,
            "test": test,
            "recognizer": recognizer,
            "entities": entities,
            "argnames": mark.args[0],
            # Tuples become lists through JSON; the consumer normalizes.
            "rows": mark.args[1],
        })
        break

json.dump(out, sys.stdout, ensure_ascii=False, default=list)
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--presidio", required=True)
    ap.add_argument("--python", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    # Reuse the static extractor's normalization so a computed table and a
    # literal one produce identical case objects.
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import extract_fixtures as fx

    root = os.path.join(args.presidio, "presidio-analyzer")
    proc = subprocess.run(
        [args.python, "-c", CHILD, root, json.dumps(TABLES)],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        print(proc.stderr[-3000:], file=sys.stderr)
        return 2

    tables = []
    for raw in json.loads(proc.stdout):
        argnames = fx.parse_argnames_from_string(raw["argnames"])
        cases = fx.build_cases(argnames, raw["rows"], raw["entities"])
        tables.append({
            "recognizer": raw["recognizer"],
            "entities": raw["entities"],
            "file": os.path.join("presidio-analyzer", raw["file"]),
            "test": raw["test"],
            "fixture": "recognizer",
            "argnames": argnames,
            "cases": cases,
        })

    total = sum(len(t["cases"]) for t in tables)
    payload = {
        "schema_version": 1,
        "note": "tables whose parametrize values are computed at import time",
        "source": {
            "repo": "data-privacy-stack/presidio",
            "commit": fx.git_commit(args.presidio),
        },
        "stats": {
            "tables": len(tables),
            "cases": total,
            "recognizers": len({t["recognizer"] for t in tables}),
        },
        "recognizers": sorted({t["recognizer"] for t in tables}),
        "entity_types": sorted({e for t in tables for e in t["entities"]}),
        "tables": tables,
        "skipped": [],
    }
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False)
        fh.write("\n")

    print(f"wrote {args.out} ({os.path.getsize(args.out) / 1024:.0f} KB)")
    print(f"  {len(tables)} tables, {total} cases")
    for t in tables:
        print(f"    {t['recognizer']}: {len(t['cases'])} cases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
