#!/usr/bin/env python3
"""Dump Python `regex`-module character-class membership for every codepoint.

This is the reference side of the backend decision gate (PLAN.md §5, decision 1).

Presidio does `import regex as re` -- NOT stdlib `re` -- so the reference
semantics are the third-party module's, which follows UTS#18. ICU (and
therefore NSRegularExpression) and PCRE2 both use different word-character
definitions, and since 131 of 155 Presidio patterns contain `\\b`, a mismatch
shows up as missed or fabricated PII.

Output is a JSON file of sorted codepoint ranges per class, which the Swift
side compares against.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import unicodedata

try:
    import regex
except ImportError:  # pragma: no cover
    print("error: pip install regex", file=sys.stderr)
    raise SystemExit(2)

MAX_CODEPOINT = 0x10FFFF
SURROGATES = range(0xD800, 0xE000)

CLASSES = {
    "w": r"\w",
    "d": r"\d",
    "s": r"\s",
}


def ranges(members: list[int]) -> list[tuple[int, int]]:
    """Collapse a sorted codepoint list into inclusive ranges."""
    out: list[tuple[int, int]] = []
    for cp in members:
        if out and cp == out[-1][1] + 1:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out


SWIFT_HEADER = '''\
// Generated by Tools/unicode_classes_python.py -- do not edit.
//
// Character-class membership tables extracted from Python's `regex` module
// version {regex_version}, which is what Presidio matches with. These are
// shipped as source rather than read from the host's ICU because ICU's Unicode
// data version varies by platform and OS release, which would make `\\b`
// behave differently on Android, macOS and Windows. See
// docs/decisions/0001-regex-backend.md.
//
// Ranges are inclusive and sorted, so membership is a binary search.

public enum UnicodeTables {{

    /// Inclusive, sorted, non-overlapping codepoint ranges.
    public typealias Table = [(lo: UInt32, hi: UInt32)]

    @inlinable
    public static func contains(_ table: Table, _ scalar: Unicode.Scalar) -> Bool {{
        let value = scalar.value
        var lo = 0
        var hi = table.count - 1
        while lo <= hi {{
            let mid = (lo + hi) / 2
            let entry = table[mid]
            if value < entry.lo {{ hi = mid - 1 }}
            else if value > entry.hi {{ lo = mid + 1 }}
            else {{ return true }}
        }}
        return false
    }}

    /// The `regex` module version these tables were generated from. A change
    /// here must be a deliberate, reviewed diff.
    public static let sourceVersion = "{regex_version}"
'''


def emit_swift(path: str, tables: dict[str, list[tuple[int, int]]], version: str) -> None:
    lines = [SWIFT_HEADER.format(regex_version=version)]
    doc = {
        "word": r"`\w` -- UTS#18 word characters. `\b` is defined in terms of this.",
        "digit": r"`\d` -- decimal digits.",
        "whitespace": r"`\s` -- whitespace.",
    }
    for name, rngs in tables.items():
        lines.append("")
        lines.append(f"    /// {doc[name]}")
        lines.append(f"    /// {len(rngs)} ranges.")
        lines.append(f"    public static let {name}: Table = [")
        for i in range(0, len(rngs), 4):
            chunk = rngs[i:i + 4]
            body = " ".join(
                f"(0x{lo:04X}, 0x{hi:04X})," for lo, hi in chunk
            )
            lines.append(f"        {body}")
        lines.append("    ]")

    lines.append("")
    lines.append("    @inlinable")
    lines.append("    public static func isWord(_ s: Unicode.Scalar) -> Bool "
                 "{ contains(word, s) }")
    lines.append("    @inlinable")
    lines.append("    public static func isDigit(_ s: Unicode.Scalar) -> Bool "
                 "{ contains(digit, s) }")
    lines.append("    @inlinable")
    lines.append("    public static func isWhitespace(_ s: Unicode.Scalar) -> Bool "
                 "{ contains(whitespace, s) }")
    lines.append("}")
    lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--swift-out", help="also emit a Swift source table")
    args = ap.parse_args()

    result: dict[str, object] = {
        "regex_version": regex.__version__,
        "unicode_version": unicodedata.unidata_version,
        "max_codepoint": MAX_CODEPOINT,
        "note": "membership per codepoint for the third-party `regex` module",
    }

    for key, pattern in CLASSES.items():
        compiled = regex.compile(pattern, regex.UNICODE)
        members = []
        for cp in range(MAX_CODEPOINT + 1):
            if cp in SURROGATES:
                continue
            if compiled.fullmatch(chr(cp)):
                members.append(cp)
        result[key] = {
            "count": len(members),
            "ranges": ranges(members),
        }
        print(f"\\{key}: {len(members)} codepoints in "
              f"{len(result[key]['ranges'])} ranges")

    # Category breakdown for \w -- makes a later diff explainable rather than
    # just a number.
    cats: dict[str, int] = {}
    for lo, hi in result["w"]["ranges"]:
        for cp in range(lo, hi + 1):
            cat = unicodedata.category(chr(cp))
            cats[cat] = cats.get(cat, 0) + 1
    result["w_categories"] = dict(sorted(cats.items()))
    print("\\w by general category:", result["w_categories"])

    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(result, fh)
        fh.write("\n")
    print(f"wrote {args.out}")

    if args.swift_out:
        emit_swift(
            args.swift_out,
            {
                "word": [tuple(r) for r in result["w"]["ranges"]],
                "digit": [tuple(r) for r in result["d"]["ranges"]],
                "whitespace": [tuple(r) for r in result["s"]["ranges"]],
            },
            regex.__version__,
        )
        print(f"wrote {args.swift_out} "
              f"({os.path.getsize(args.swift_out) / 1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
